-- CreateEnum
CREATE TYPE "Status" AS ENUM ('PENDING_PROCESSING', 'PROCESSING', 'PENDING_MANUAL_REVIEW', 'APPROVED', 'DENIED');

-- AlterTable
ALTER TABLE "Application" ADD COLUMN     "status" "Status" NOT NULL DEFAULT 'PENDING_MANUAL_REVIEW';
