-- CreateTable
CREATE TABLE "FOIA7aLoanData" (
    "id" TEXT NOT NULL,
    "asofdate" TIMESTAMP(3) NOT NULL,
    "program" TEXT,
    "borrname" TEXT,
    "borrstreet" TEXT,
    "borrcity" TEXT,
    "borrstate" TEXT,
    "borrzip" TEXT,
    "bankname" TEXT,
    "bankfdicnumber" TEXT,
    "bankncuanumber" TEXT,
    "bankstreet" TEXT,
    "bankcity" TEXT,
    "bankstate" TEXT,
    "bankzip" TEXT,
    "grossapproval" DOUBLE PRECISION,
    "sbaguaranteedapproval" DOUBLE PRECISION,
    "approvaldate" TIMESTAMP(3),
    "approvalfiscalyear" INTEGER,
    "firstdisbursementdate" TIMESTAMP(3),
    "deliverymethod" TEXT,
    "subprogram" TEXT,
    "initialinterestrate" DOUBLE PRECISION,
    "fixedorvariableinterestind" TEXT,
    "terminmonths" INTEGER,
    "naicscode" TEXT,
    "naicsdescription" TEXT,
    "franchisecode" TEXT,
    "franchisename" TEXT,
    "projectcounty" TEXT,
    "projectstate" TEXT,
    "sbadistrictoffice" TEXT,
    "congressionaldistrict" TEXT,
    "businesstype" TEXT,
    "businessage" TEXT,
    "loanstatus" TEXT,
    "paidinfulldate" TIMESTAMP(3),
    "chargeoffdate" TIMESTAMP(3),
    "grosschargeoffamount" DOUBLE PRECISION,
    "revolverstatus" TEXT,
    "jobssupported" INTEGER,
    "soldsecmrktind" TEXT,
    "catalog_month" INTEGER,
    "catalog_year" INTEGER,

    CONSTRAINT "FOIA7aLoanData_pkey" PRIMARY KEY ("id")
);
